### ISSUE TITLE
A request about measurement board features

### ISSUE THREAD

**Issue by deedlitelf** [doodlezucc/dungeonclub#9]
Hello, doodlezucc.
First of all, thank you very much for your contribution to TRPG VTT, but I found that there is a feature missing that I need. 
In this VTT, when you try to create a second measurement board or leave the measurement board layer, the old measurement board will be automatically deleted. In most cases, this is a very convenient feature. However, in some special scenarios, I need to keep this measurement board to indicate the range, such as when a creature casts Darkness or Web, the spell should last until the effect ends. I hope there is a feature that can keep this part of the measurement board to indicate the range, or actually the tool already has similar functions, but I haven't found it yet? 
Another question is related to logical functions. Some of my friends hope that they can directly drag the token to the map instead of clicking first and then confirming the position. Of course, this is just a habit of operation, and I believe that your current design must have its own considerations. 
Thank you very much for you and your dungeonclub.

**Comment by doodlezucc** [comment]
Hi there!
It's true that measurements are currently very "short lived" in the sense of getting deleted once you're out of *measuring mode*. Thank you for mentioning Darkness and Web spells - I'll keep them in my mind while thinking of a solution. This issue actually already had a place on my private to-do list, but it's always nice to have some user input.

Regarding the UX habit you mentioned, I think it's definitely a valid enhancement request. I assume this is about the GM's token palette? Allowing a single motion drag & drop on top of the current behavior sounds good and probably can be achieved pretty easily.

Cheers!
